#include <stddef.h>
#include <Eth_cfg.h>


// This file is autogenerated, any hand modifications will be lost!



const Eth_ConfigType EthConfigs[ETH_DRIVER_MAX_CHANNEL] = {
	{
		/* Eth channel - 0 */
		.general = {
			.index = 0,
			.mainfn_period_ms = 10,
			.dev_error_detect = FALSE,
			.get_cntr_val_api = FALSE,
			.get_rx_stats_api = FALSE,
			.get_tx_stats_api = FALSE,
			.get_tx_erctv_api = FALSE,
			.get_gbl_time_api = FALSE,
			.max_ctrl_suportd = 2,
			.version_info_api = FALSE
		},
		.offload = {
			.en_cksum_ipv4 = TRUE,
			.en_cksum_icmp = FALSE,
			.en_cksum_tcp = TRUE,
			.en_cksum_udp = FALSE
		}
	},
	{
		/* Eth channel - 1 */
		.general = {
			.index = 1,
			.mainfn_period_ms = 10,
			.dev_error_detect = FALSE,
			.get_cntr_val_api = FALSE,
			.get_rx_stats_api = FALSE,
			.get_tx_stats_api = FALSE,
			.get_tx_erctv_api = FALSE,
			.get_gbl_time_api = FALSE,
			.max_ctrl_suportd = 2,
			.version_info_api = FALSE
		},
		.offload = {
			.en_cksum_ipv4 = FALSE,
			.en_cksum_icmp = TRUE,
			.en_cksum_tcp = TRUE,
			.en_cksum_udp = FALSE
		}
	},
};
